### ISSUE TITLE
In the BottomSheetExample file, if the number of lists is five, you can't scroll to the last cell

### ISSUE THREAD

**Issue by WELONG** [Wouter125/BottomSheet#14]
`                    
VStack(spacing: 0) {
                        ScrollView {
                            ForEach(0..<5, id: \.self) { _ in
                                newsRow
                            }
                        }

                        Spacer(minLength: 54)
                    }
`

**Comment by Wouter125** [comment]
Sorry, completely missed this issue. I'm currently rewriting the setup to follow Apple's new pattern. Will verify and fix it in V2.0!
