### ISSUE TITLE
License

### ISSUE THREAD

**Issue by calt** [Wouter125/BottomSheet#16]
Hi, what is the license for this library?

**Comment by Wouter125** [comment]
Sorry for my late response but MIT will be fine. Will update the readme when publishing the complete refactor which is currently opened as PR. Having a few bugs, trying to fix them in my downtime but don't have that much lately.

**Comment by anuragajwani** [comment]
License file is still missing within the project. Would be ok for me to add it in?

**Comment by anuragajwani** [comment]
I have create a PR:
https://github.com/Wouter125/BottomSheet/issues/35
