### ISSUE TITLE
Cannot find 'BottomSheetView' in scope

### ISSUE THREAD

**Issue by Suguru-Tokuda** [Wouter125/BottomSheet#29]
Xcode version: 15.0.1
BottomSheet version: 2.0.1

I added an import for BottomSheet in a SwiftUI View file. When I call BottomSheetView just like an example in the README.md:

```
BottomSheetView(
    position: $position,
    animationCurve: SheetAnimation(
        mass: 1,
        stiffness: 250,
        damping: 25
    ),
    background: (
        Color(UIColor.secondarySystemBackground)
    ),
    header: { },
    content: {
        EmptyView()
            .onSheetDrag(translation: $settings.translation)
    }
}
```

I get an compiler error: Cannot find 'BottomSheetView' in scope

**Comment by isaacjones99** [comment]
I have the same issue. It looks like the view BottomSheetView no longer exists in the source code.

You can work around this by using version 1.4.5

**Comment by Suguru-Tokuda** [comment]
I had to downgrade the package to 1.4.5 to get BottomSheetView to work.

**Comment by Wouter125** [comment]
Hi everyone! This is not a bug but intended behavior. 2.0.0 is a major in semver and comes with breaking changes. There no longer is a BottomSheetView but a sheetPlus view modifier. It can be added to any view. So it now works in the same way as the official Apple implementation. This way if you upgrade to the latest iOS you just have to remove the word Plus and you get the native one!

Please see the readme and the attached examples for implementation guidance.

This version has everything the 1.4.5 version had but the implementation improved and has more additional modifiers. Let me know if there are any other issues!

**Comment by Suguru-Tokuda** [comment]
If you have removed it, it's better to edit your documentation. It's very confusing.

**Comment by Wouter125** [comment]
@Suguru-Tokuda sorry missed that part. Updated the documentation!
