### ISSUE TITLE
there is no BottomSheetView

### ISSUE THREAD

**Issue by nurgun795** [Wouter125/BottomSheet#37]
hi how i can find BottomSheetView i imported BottomSheet but there is no module of BottomSheetView

**Comment by nurgun795** [comment]
<img width="1436" alt="Screen Shot 2024-06-26 at 4 00 34 PM" src="https://github.com/Wouter125/BottomSheet/assets/170812617/091148ba-0ef0-4ba7-a7bd-1dc5933f6b9e">
<img width="1423" alt="Screen Shot 2024-06-26 at 4 00 52 PM" src="https://github.com/Wouter125/BottomSheet/assets/170812617/2d0c4cca-d58d-492c-894e-cbc87b9910dc">

**Comment by nurgun795** [comment]
<img width="1426" alt="Screen Shot 2024-07-02 at 6 43 37 PM" src="https://github.com/Wouter125/BottomSheet/assets/170812617/1a86bcbd-9ae7-4977-82bb-872ead9ebfa0">
<img width="1375" alt="Screen Shot 2024-07-02 at 6 43 52 PM" src="https://github.com/Wouter125/BottomSheet/assets/170812617/7852be40-079e-4821-9b1f-a514ab54f7cf">

**Comment by Wouter125** [comment]
There is no view. There only is a view modifier on where you want to attach it. Please see the examples in the bundle and the documentation here: https://github.com/Wouter125/BottomSheet?tab=readme-ov-file#how-to-use.
