### ISSUE TITLE
Scroll view moves to the top after position changing

### ISSUE THREAD

**Issue by ValeriyJefimov** [Wouter125/BottomSheet#6]
Hey. Thanx for such awesome lib)

To reproduce:
In sample app drag sheet to top position, the drag content even higher. Then drag header to any other position without touching content. After that try to drag content.

**Comment by Wouter125** [comment]
I see, will fix tonight. It's still in beta for a bit, because I'm adding more features on the go to get it stable.

**Comment by Wouter125** [comment]
@ValeriyJefimov I temporarily implemented a quick fix to resolve this problem. If it still persists let me know. I'll build a better implementation when I find some more time, because it can still happen on some edge cases right now.

**Comment by Wouter125** [comment]
Just implemented a proper fix. Let me know if you encounter any other issues. If you update to 1.4.2 you should be good.
